### Create fundraising event
POST http://localhost:8080/api/fundraising-events
Content-Type: application/json

{
  "name": "Caritas",
  "currency": "PLN"
}

###
POST http://localhost:8080/api/fundraising-events
Content-Type: application/json

{
  "name": "WOSP",
  "currency": "EUR"
}

###
POST http://localhost:8080/api/fundraising-events
Content-Type: application/json

{
  "name": "PCK",
  "currency": "PLN"
}

### Show report
GET http://localhost:8080/api/fundraising-events/report
Accept: application/json


